ALTER TABLE tours ADD COLUMN IF NOT EXISTS is_slide BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS slide_text TEXT;
ALTER TABLE tours ADD COLUMN IF NOT EXISTS slide_audio_path VARCHAR(512);
ALTER TABLE tours ADD COLUMN IF NOT EXISTS slide_audio_original_name VARCHAR(512);
